<ColorScreen>:
    name: 'color'
    asd: asd
    on_enter: root.APLE()
    FloatLayout:
        size_hint: None, None
    ColPckr:
        on_color: root.ColorLarge(self.color[0], self.color[1], self.color[2], self.color[3])
        ImageButton:
            id: asd
            size: 640, 525
            center_x: root.width * 0.249
            center_y: root.height * 0.32
            source: "despacito.png"
            on_press:root.goBack()
