<MainScreen>:
    name: 'main'
    FloatLayout:
        size_hint: None, None

    CustomImage:
        source: "rgb3.jpeg"
        allow_stretch: True
        keep_ratio: True

    DPEAButton:
        size: 200, 200
        center_x: root.width * 0.5
        center_y: root.height * 0.5

        background_color: 0,0,0,0
        color: 0.035, 0.152, 0.725, 1

        text: "Idle movement"
        on_press:root.idle()



